# Generated by Django 5.2.8 on 2025-11-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pre_req',
            field=models.ManyToManyField(blank=True, to='account.course'),
        ),
    ]
